<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6798" started-at="2017-04-28T05:57:18Z" finished-at="2017-04-28T05:57:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6798" started-at="2017-04-28T05:57:18Z" finished-at="2017-04-28T05:57:25Z">
      <class name="test.java.com.recaptcha.servlet.TestLoginServletTest">
        <test-method status="PASS" signature="testVerifyCaptchaApiFalse()[pri:0, instance:test.java.com.recaptcha.servlet.TestLoginServletTest@39aeed2f]" name="testVerifyCaptchaApiFalse" duration-ms="6238" started-at="2017-04-28T11:27:18Z" finished-at="2017-04-28T11:27:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVerifyCaptchaApiFalse -->
        <test-method status="FAIL" signature="testVerifyCaptchaApiTrue()[pri:0, instance:test.java.com.recaptcha.servlet.TestLoginServletTest@39aeed2f]" name="testVerifyCaptchaApiTrue" duration-ms="539" started-at="2017-04-28T11:27:24Z" finished-at="2017-04-28T11:27:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at test.java.com.recaptcha.servlet.TestLoginServletTest.testVerifyCaptchaApiTrue(TestLoginServletTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVerifyCaptchaApiTrue -->
      </class> <!-- test.java.com.recaptcha.servlet.TestLoginServletTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
